### ISSUE TITLE
Erratic behavior of `chafa -f iterm image.jpg` on Windows

### ISSUE THREAD

**Issue by ykhan21** [hpjansson/chafa#194] opened 2024-03-17 04:56 UTC
Setup:

On Windows:
1. Install scoop, run `scoop bucket add main`, run `scoop bucket add extras`, and finally run `scoop install git wezterm chafa`.
2. Use [this](https://github.com/hpjansson/chafa/assets/51864191/9707427c-1ae9-4fa7-9569-3e7da4b1fe2f) image.
3. Set Wezterm's default shell to the bash shell that was installed with `scoop install git`. To do this, create a ~/.wezterm.lua file with these contents:
```lua
local wezterm = require 'wezterm'
local config = {}
config.default_prog = { 'c:/users/USERNAME/scoop/apps/git/current/bin/bash.exe -i -l' }
return config
```
See https://wezfurlong.org/wezterm/config/files.html for more details.

Problem:

On Wezterm, `chafa -f iterm image.jpg` sometimes outputs extra space at the end like so:
![image](https://github.com/hpjansson/chafa/assets/51864191/1045766f-6d40-4ecc-9051-77b7b029e924)

Notice that the shell prompt starts at the bottom right of the image above.

On mintty (the terminal called Git Bash that is installed when you install Git for Windows is mintty), most of the time, `chafa -f iterm image.jpg` does not display an image and instead results in a large amount of whitespace, almost as if it were displaying an empty image. Very rarely it displays a distorted half of the image. The `showimg` script found [here](https://github.com/mintty/utils/blob/master/showimg) works correctly to show images in mintty (Git Bash) in the iterm format.

**Comment by AnonymouX47** [comment] 2024-03-17 13:19
Duplicate of #186

**Comment by hpjansson** [comment] 2024-03-17 15:21
Thanks for filing the issue, @ykhan21. I think @AnonymouX47 is right - the short version is that Chafa is a native Windows app, and the Wezterm binary is a Cygwin app. These are different platforms that don't play well together. We need to add Cygwin builds (or alternatively, other apps should be made native).

**Comment by hpjansson** [comment] 2024-10-11 00:14
Closing as duplicate. I don't have the bandwidth to do Cygwin builds too at the moment, but if you get it working there, I'd love to hear about it.

**Closed** 2024-10-11 00:14 UTC

**Comment by ykhan21** [comment] 2024-10-11 20:26
@hpjansson, are there any drawbacks to having the only Windows build of chafa be cygwin, like Wezterm? Can't you then use it in both native and cygwin terminals?

**Comment by hpjansson** [comment] 2024-10-13 02:26
The biggest drawbacks are:

- We'd need to distribute the `cygwin1.dll` runtime in addition to the program and ensure it can be found in the link path. Currently we only have to ship `chafa.exe`, which you can run from any path. The Cygwin FAQ claims it's [infeasible to link statically](https://cygwin.com/faq/faq.html#faq.programming.static-linking) (outdated? no idea).
- I build by cross-compiling, so we'd have to find a decent cross-compiling environment (Linux -> Cygwin). I currently use MXE (Linux -> win32), which is more or less perfect for this. Probably just a matter of doing the research.
- I'd like to distribute `chafa.dll` plus headers for windows at some point in the future - it'd need to work in MSVC though, so with native runtime. Most of the issues I've had with bigger and more complex win32 projects in the past stemmed from the fact that native and Cygwin libraries don't mix, but still get mixed up easily. I haven't actually seen any demand from Windows developers though, so it isn't *that* important.

So it's a good question. My opinion on this was forged in battle about 25 years ago, and maybe things have changed, or it doesn't matter that much anymore. Help with research and testing is very welcome!
