### ISSUE TITLE
Incorrect aspect ratio

### ISSUE THREAD

**Issue by johnd0e** [hpjansson/chafa#214] opened 2024-08-30 10:24 UTC
Chafa version 1.14.2, Windows

```
chafa -f symbols file.jpg
chafa -f sixels file.jpg
```

Outputs images that are too narrow.
And with sixels image is too small, perhaps that is wrong too.

[sample.zip](https://github.com/user-attachments/files/16815519/sample.zip)

**Comment by hpjansson** [comment] 2024-08-31 12:24
The size issue is probably #211. There's a test binary there too. The aspect issue is #212, I think, but that one needs some work still. Shouldn't be too long.

**Comment by hpjansson** [comment] 2024-09-05 23:19
I think this is fixed now. It'll be in the next release. Thanks for reporting it!

**Comment by johnd0e** [comment] 2024-09-14 18:59
> I think this is fixed now. It'll be in the next release.

Now the image has proper size, but still distorted a bit.
Too narrow.

**Comment by hpjansson** [comment] 2024-09-15 13:42
> Now the image has proper size, but still distorted a bit. Too narrow.

Could you attach the source image, plus a screenshot showing how it's displayed in the terminal and the command line you used? I'll take another look.

**Comment by johnd0e** [comment] 2024-09-21 11:04
Source 1024*1024:
![result](https://github.com/user-attachments/assets/b4b597e7-be33-4503-b41f-6b173e6fff6f)

Appearance in terminal:
![Capture](https://github.com/user-attachments/assets/979ab377-429c-46de-8d6d-3c325f0a5985)

Command: `chafa -f sixels result.jpg`

**Comment by j4james** [comment] 2024-09-21 11:35
@johnd0e If you're using Windows Terminal, the behavior you're seeing is by design. It's intended that a given sixel image will occupy the same number of cells, independent of the font or font size that is in use at the time. For example your 1024x1024 image will always occupy a little over 102 columns and 51 rows.  If your font has an aspect ratio that is significantly different from 2:1, it's expected that it would appear somewhat distorted.

**Comment by johnd0e** [comment] 2024-09-21 11:40
> If you're using Windows Terminal, the behavior you're seeing is by design.

Ok, I believe that it is useful for some use cases.
But not for others.

Could you then implement "correct aspect ratio" as an option?

**Comment by j4james** [comment] 2024-09-21 11:59
> Shouldn't then the "correct aspect ratio" be implement as an option?

That's not something I'm personally interested in implementing, but you're welcome to request that feature on the WT issue tracker.

> Perhaps [`CSI 14 t` and `CSI 18 t`](https://github.com/hpjansson/chafa/issues/211#issuecomment-2298971470) can give the proper value?

`CSI 14 t` has to return the emulated pixel size, otherwise software that relies on that to calculate the cell size won't work.

**Comment by hpjansson** [comment] 2024-09-21 15:30
Sounds like this is working to its full potential. I'll close the issue, but feel free to keep discussing (although, as James points out, it'd likely be more productive in the WT tracker). Thanks!

**Closed by hpjansson** 2024-09-21 15:30 UTC

**Comment by johnd0e** [comment] 2024-10-21 00:10
@hpjansson 
Is it possible to force specific aspect ration with command line option?

**Comment by hpjansson** [comment] 2024-10-21 06:50
@johnd0e You can set the output size with `-s` and add `--stretch` to fill the dimensions exactly. In theory, you should also be able to use `--font-ratio`, but I think I broke it in one of the recent releases.

**Comment by johnd0e** [comment] 2024-10-23 14:37
> In theory, you should also be able to use --font-ratio, but I think I broke it in one of the recent releases.

That's right, it's broken(
