### ISSUE TITLE
build error: aarch64, git master 2021-09-25

### ISSUE THREAD

**Issue by clort81** [hpjansson/chafa#66] opened 2021-09-25 08:16 UTC
```
libtool: link: gcc -Wall -Wextra -Wmissing-prototypes -ffast-math -fvisibility=hidden -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/aarch64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/aarch64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/local/include/libpng17 -I/usr/include/freetype2 -O2 -ffast-math -ftree-vectorize -fno-strict-overflow -funsafe-math-optimizations -march=armv8-a+crypto+crc+aes+sha2 -Wl,-Bsymbolic -o .libs/chafa chafa-chafa.o chafa-file-mapping.o chafa-font-loader.o chafa-gif-loader.o chafa-named-colors.o chafa-xwd-loader.o  -lglib-2.0 /usr/lib/aarch64-linux-gnu/libMagickWand-6.Q16.so /usr/lib/aarch64-linux-gnu/libMagickCore-6.Q16.so -lfreetype ../../chafa/.libs/libchafa.so ../../libnsgif/.libs/libnsgif.a -pthread -fopenmp -Wl,-rpath -Wl,/usr/local/lib
/usr/bin/ld: chafa-chafa.o: in function `build_string':
chafa.c:(.text+0x7ac): undefined reference to `chafa_canvas_config_set_fg_only_enabled'
/usr/bin/ld: chafa.c:(.text+0x82c): undefined reference to `chafa_canvas_config_set_optimizations'
/usr/bin/ld: chafa.c:(.text+0x85c): undefined reference to `chafa_canvas_print'
/usr/bin/ld: chafa-chafa.o: in function `run':
chafa.c:(.text+0x11dc): undefined reference to `chafa_term_info_emit_cursor_to_top_left'
/usr/bin/ld: chafa.c:(.text+0x13e8): undefined reference to `chafa_term_info_emit_cursor_to_top_left'
/usr/bin/ld: chafa.c:(.text+0x1618): undefined reference to `chafa_term_info_emit_clear'
/usr/bin/ld: chafa.c:(.text+0x1624): undefined reference to `chafa_term_info_emit_cursor_to_top_left'
/usr/bin/ld: chafa.c:(.text+0x163c): undefined reference to `chafa_term_info_emit_cursor_up'
/usr/bin/ld: chafa.c:(.text+0x19f4): undefined reference to `chafa_term_info_emit_cursor_up'
/usr/bin/ld: chafa.c:(.text+0x1a04): undefined reference to `chafa_term_info_emit_clear'
/usr/bin/ld: chafa.c:(.text+0x1a14): undefined reference to `chafa_term_info_emit_cursor_to_top_left'
/usr/bin/ld: chafa-chafa.o: in function `parse_options':
chafa.c:(.text+0x21fc): undefined reference to `chafa_term_db_get_default'
/usr/bin/ld: chafa.c:(.text+0x2204): undefined reference to `chafa_term_db_detect'
/usr/bin/ld: chafa.c:(.text+0x2210): undefined reference to `chafa_term_info_have_seq'
/usr/bin/ld: chafa.c:(.text+0x2220): undefined reference to `chafa_term_info_have_seq'
/usr/bin/ld: chafa.c:(.text+0x2230): undefined reference to `chafa_term_info_have_seq'
/usr/bin/ld: chafa.c:(.text+0x2240): undefined reference to `chafa_term_info_have_seq'
/usr/bin/ld: chafa.c:(.text+0x2250): undefined reference to `chafa_term_info_have_seq'
/usr/bin/ld: chafa-chafa.o:chafa.c:(.text+0x2260): more undefined references to `chafa_term_info_have_seq' follow
/usr/bin/ld: chafa-chafa.o: in function `parse_options':
chafa.c:(.text+0x2290): undefined reference to `chafa_term_db_get_default'
/usr/bin/ld: chafa.c:(.text+0x2298): undefined reference to `chafa_term_db_get_fallback_info'
/usr/bin/ld: chafa.c:(.text+0x22a8): undefined reference to `chafa_term_info_supplement'
/usr/bin/ld: chafa.c:(.text+0x22b4): undefined reference to `chafa_term_info_unref'
/usr/bin/ld: chafa.c:(.text+0x262c): undefined reference to `chafa_term_info_have_seq'
/usr/bin/ld: chafa.c:(.text+0x2658): undefined reference to `chafa_term_info_have_seq'
/usr/bin/ld: chafa.c:(.text+0x2734): undefined reference to `chafa_term_info_have_seq'
/usr/bin/ld: chafa.c:(.text+0x2758): undefined reference to `chafa_term_info_have_seq'
/usr/bin/ld: chafa.c:(.text+0x2770): undefined reference to `chafa_term_info_have_seq'
/usr/bin/ld: chafa-chafa.o:chafa.c:(.text+0x27bc): more undefined references to `chafa_term_info_have_seq' follow
/usr/bin/ld: chafa-chafa.o: in function `main':
chafa.c:(.text.startup+0x1bc): undefined reference to `chafa_term_info_unref'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_work_cell_init'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_iterm2_canvas_draw_all_pixels'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_iterm2_canvas_new'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_kitty_canvas_draw_all_pixels'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_work_cell_get_mean_colors_for_symbol'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_term_info_emit_begin_sixels'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_prepare_pixel_data_for_symbols'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_term_info_ref'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_iterm2_canvas_destroy'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_work_cell_get_median_colors_for_symbol'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_iterm2_canvas_build_ansi'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_work_cell_to_bitmap'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_term_info_emit_end_sixels'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_term_info_get_seq'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_ascii_dec_u8'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_canvas_print_symbols'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_work_cell_calc_mean_color'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_kitty_canvas_destroy'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_kitty_canvas_build_ansi'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_work_cell_get_contrasting_color_pair'
/usr/bin/ld: ../../chafa/.libs/libchafa.so: undefined reference to `chafa_kitty_canvas_new'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:445: chafa] Error 1
make[3]: Leaving directory '/media/sd/pcbak2/Projects/ascii/chafa/tools/chafa'
make[2]: *** [Makefile:370: all-recursive] Error 1
make[2]: Leaving directory '/media/sd/pcbak2/Projects/ascii/chafa/tools'
make[1]: *** [Makefile:477: all-recursive] Error 1
make[1]: Leaving directory '/media/sd/pcbak2/Projects/ascii/chafa'
make: *** [Makefile:386: all] Error 2
```
anyone else getting this?  i've run make clean...

**Comment by hpjansson** [comment] 2021-09-25 23:29
Hi, thanks for filing the issue. I haven't come across this in any of my builds. Could you please supply:

- Name and version of your OS
- Output from `libtoolize --version ; automake --version ; autoconf --version`
- The files `log.txt` and `config.log` after running `( make distclean ; ./autogen.sh ; make ) >log.txt 2>&1`

Note that it's not always enough to run `make clean`, you may want to try `make distclean` before running `./autogen.sh`. And if you already have Chafa installed in `/usr` or `/usr/local`, you may want to remove it from there too (look for `libchafa.so`).

**Comment by clort81** [comment] 2021-09-26 05:01
Thanks for the reply! 
Turns out distclean is all i needed:

make distclean
./autogen.sh
./configure 
make
---
--- Success! You can now run tools/chafa/chafa, or install everything
--- using make install or sudo make install.
---

OS is a bit of this and a bit of that..
libtoolize 2.4.6
automake 1.16.3
autoconf: 2.69
If you still want log.txt of the full build, let me know.

Thanks for chafa!  

I used to make PETSCII on original commodore PET. I have modified dejavu sans mono  ◢ ◣ ◥ ◤ to be full-width/height.  Do you know terminal fonts that feature all the graphics charactersfrom Unicode 13.0?  I find only http://viznut.fi/unscii/

I'd be happy to modify more fonts to have full/correct graphics characters, if this can be coordinated and published.

Cheers!

**Comment by hpjansson** [comment] 2021-09-26 16:46
> Turns out distclean is all i needed:

Great! Autotools are supposed to regenerate build files when the dependencies change, but in practice it can be hit and miss.

> If you still want log.txt of the full build, let me know.

Nah, no need. If it's just an isolated incident, I think it'd take more effort to track down the cause that it's worth -- it might not even be something that can be fixed in Chafa proper. Of course, if it keeps happening, that'd change the calculus :)

> Thanks for chafa!
> 
> I used to make PETSCII on original commodore PET. I have modified dejavu sans mono ◢ ◣ ◥ ◤ to be full-width/height. Do you know terminal fonts that feature all the graphics charactersfrom Unicode 13.0? I find only http://viznut.fi/unscii/

An actual PETSCII artist, wow -- I still have the C64 I grew up with, but I didn't make it very far on that platform creatively. I'd love to hear if there are ways Chafa can be more useful in vintage pseudographics.

The terminals I use substitute alternate fonts for missing glyphs, so I haven't given much thought to which font is more complete. Some terminals also generate many of the block symbols themselves without using a font. Personally I used Terminus until the font stack lost support for bitmap fonts (boo) -- I think it was pretty popular. DejaVu Sans Mono, Hack, Source Code Pro are other popular examples, but I haven't mapped out what their block symbol support is like.

Unscii looks like a great resource, thanks for the link. 

> I'd be happy to modify more fonts to have full/correct graphics characters, if this can be coordinated and published.

That would be absolutely brilliant. I'll help if I can. Have you contacted any upstream font maintainers?

**Comment by clort81** [comment] 2021-09-26 21:12
Some kid at debian disabled pcf/x11 bitmap fonts: "bitmap fonts are of lower quality"

dpkg-reconfigure fontconfig-config

Third screen lets you re-enable X11 pcf fonts.

Xft font rendering does provide fallback, but the > 4byte unicode codepoints aren't supported in xterm, etc.  This is another thing to fix someday.  

I'll submit patched fonts to nerdfonts.com and contact the respective upstream maintainers, time allowing.

**Closed** 2021-09-26 21:12 UTC

**Comment by hpjansson** [comment] 2021-09-26 22:29
@clort81 The issue that sank bitmap fonts for me was this one: https://gitlab.gnome.org/GNOME/pango/-/issues/386 -- my distro only has the TTF conversion of Terminus, which is unacceptably blurry. I should probably look into packaging an OTB version with embedded bitmaps.

I started a discussion here: https://github.com/hpjansson/chafa/discussions/68

Feel free to use it to coordinate.
