### ISSUE TITLE
tmux show picture is blur

### ISSUE THREAD

**Issue by newyorkthink** [hpjansson/chafa#116] opened 2022-11-23 14:18 UTC
![image](https://user-images.githubusercontent.com/87791643/203569371-f6245407-2d4d-428c-b5b9-1f47effc392f.png)

i try use 256 ,not work

![image](https://user-images.githubusercontent.com/87791643/203569520-1a84327e-8052-4266-8d26-0907bb0bfe78.png)

**Comment by newyorkthink** [comment] 2022-11-23 14:58
viu is too
https://github.com/atanunq/viu/issues/106

**Comment by hpjansson** [comment] 2022-11-23 20:05
Hi, thanks for filing the bug.

What you're seeing is artifacts in symbol mode, since we can only use two colors per cell. For some images you can get better results if you specify `--color-extractor median`. This should result in less blurring, but potentially more noise instead.

**Comment by newyorkthink** [comment] 2022-11-25 10:18
I issus tmux 
https://github.com/tmux/tmux/issues/3395

**Comment by hpjansson** [comment] 2022-11-28 02:21
If the issue is that you're getting symbol mode in tmux, that's unfortunately due to tmux not supporting images. There's nothing we can do about that in Chafa, unfortunately.

There is a sixel-capable fork of tmux, maybe you'll have some luck with that: https://github.com/csdvrx/tmux

Then to get sixel output in Chafa, use `chafa -f sixel`.

**Comment by hpjansson** [comment] 2023-01-02 23:03
@newyorkthink Ping -- did you manage to fix your issue?

**Comment by newyorkthink** [comment] 2023-01-04 15:58
I sorry , i have not time to find question. and not fix it

**Comment by newyorkthink** [comment] 2023-01-04 15:58
![image](https://user-images.githubusercontent.com/87791643/210596294-6e8a6ecf-1f87-4f7b-a432-a6c826caf63a.png)

**Comment by newyorkthink** [comment] 2023-01-04 15:59
![image](https://user-images.githubusercontent.com/87791643/210596348-0c8cdd77-953c-4442-9184-8540e48dc3cd.png)

**Comment by hpjansson** [comment] 2023-01-05 00:47
I see. I'm sorry, it's not possible to produce better quality inside tmux. This can only be improved in tmux itself. You must either avoid tmux or use a tmux fork with image support (for instance, the sixel-capable fork I linked to above).

I'll close this now. Feel free to reopen if the situation changes, or open another issue if you have other questions/bugs to report. Thanks.

**Closed by hpjansson** 2023-01-05 00:47 UTC

**Comment by m040601** [comment] 2023-09-03 17:30
Just to give my 2 cents feedback.

This is not a request. I am a very big fan of chafa and I am perfectly satisfied with what it does and what it does not. I'm not a programmer, but I am well aware of all the constraints that tmux imposes



> [hpjansson] said
> ...
> I'm sorry, it's not possible to produce better quality inside tmux. This can only be improved in tmux itself. You must either avoid tmux or ...
> ....
> 


And yet "timg" was in the same "situation" and they somehow "managed" to overcome this, https://github.com/hzeller/timg/issues/95



That is "timg" inside tmux inside kitty can see perfect images.

This is working as on my Archlinux system

$ timg --version

timg 1.5.2+  <https://timg.sh/>
Copyright (c) 2016..2023 Henner Zeller. This program is free software; license GPL 2.0.

Image decoding GraphicsMagick 1.3.41 (2023-08-12)
Openslide 3.4.1
Turbo JPEG
QOI image loading
swscale 7.1.100
Video decoding libav 60.3.100; avdevice 60.1.100
Half, quarter, iterm2, and kitty graphics output: timg builtin.
Libsixel version 1.10.3

Installed from here, https://aur.archlinux.org/packages/timg

$ kitty --version

kitty 0.29.2 created by Kovid Goyal

$ tmux -V

tmux 3.3a





But,

```
chafa -f kitty cruZ6cSl_o.jpg
```


   $ chafa --version

```
Chafa version 1.12.4

Loaders:  GIF ImageMagick JPEG PNG SVG TIFF WebP XWD
Features: mmx sse4.1 popcnt
Applying: mmx

Copyright (C) 2018-2022 Hans Petter Jansson et al.
Incl. libnsgif copyright (C) 2004 Richard Wilson, copyright (C) 2008 Sean Fox
Incl. LodePNG copyright (C) 2005-2018 Lode Vandevenne

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
````

**Comment by hpjansson** [comment] 2023-09-03 21:21
@m040601 Looks like the feature was introduced some time after I closed this. We should be able to support it without too much trouble.

I'll open a new issue to track it - thanks for bringing it up!
